language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install

before_script:
  - pecl config-set preferred_state beta
  - printf "yes\n" | pecl install apcu
  - printf "apc.enable_cli=1" > apcu.ini
  - phpenv config-add apcu.ini

script:
  - vendor/bin/phpunit
